spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jpasecurity?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: qwer1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    generate-ddl: false

server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
  port: 8099